### ISSUE TITLE
Observer was not registered

### ISSUE THREAD

**Issue by Mikhael9** [florent37/MaterialViewPager#198]
Hi,
I've a little issue with this library. Something, when I press back in my application it retrieve me this error

"2-18 22:55:46.911 32267-32267/it.tuttoandroid E/AndroidRuntime: FATAL EXCEPTION: main
                                                                 Process: it.tuttoandroid, PID: 32267
                                                                 java.lang.IllegalStateException: Observer com.astuetz.PagerSlidingTabStrip$PagerAdapterObserver@b18ddbf was not registered.
                                                                     at android.database.Observable.unregisterObserver(Observable.java:69)
                                                                     at android.support.v4.view.PagerAdapter.unregisterDataSetObserver(PagerAdapter.java:294)
                                                                     at com.astuetz.PagerSlidingTabStrip.onDetachedFromWindow(PagerSlidingTabStrip.java:548)
                                                                     at android.view.View.dispatchDetachedFromWindow(View.java:14795)
                                                                     at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3138)
                                                                     at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3135)"

This is my code when register recyclerview in my fragment

MaterialViewPagerHelper.registerRecyclerView(getActivity(), mRecyclerView, new EndlessRecyclerOnScrollListener(mLayoutManager) {
            @Override
            public void onLoadMore(int current_page) {

                count = count + 1;
                caricaAsyncTask(url + count, 3);
            }
        });

Please, help me!
Thanks!

**Comment by bloder** [comment]
probably this error is occurring when you set your adapter, show me how you're setting the adapter, maybe I can help you
