### ISSUE TITLE
java.lang.NullPointerException   at com.github.florent37.materialviewpager.MaterialViewPager.onFinishInflate(MaterialViewPager.java:154)

### ISSUE THREAD

**Issue by hindber** [florent37/MaterialViewPager#210]
Hello, I'm new to MaterialViewPager and I want some help please with these : 

 Rendering Problems java.lang.NullPointerException   at com.github.florent37.materialviewpager.MaterialViewPager.onFinishInflate(MaterialViewPager.java:154)   at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:814)   at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:64)   at android.view.LayoutInflater.rInflate(LayoutInflater.java:782)   at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:809)   at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:64)   at android.view.LayoutInflater.rInflate(LayoutInflater.java:782)   at android.view.LayoutInflater.inflate(LayoutInflater.java:504)   at android.view.LayoutInflater.inflate(LayoutInflater.java:385) 
 

My code is : 

<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools" xmlns:app="http://schemas.android.com/apk/res-auto" android:layout_width="match_parent"
    android:layout_height="match_parent" android:paddingLeft="@dimen/activity_horizontal_margin"
    android:paddingRight="@dimen/activity_horizontal_margin"
    android:paddingTop="@dimen/activity_vertical_margin"
    android:paddingBottom="@dimen/activity_vertical_margin" tools:context=".Menu">

    <com.github.florent37.materialviewpager.MaterialViewPager
        android:id="@+id/materialViewPager"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:viewpager_logo="@layout/header"
        app:viewpager_logoMarginTop="100dp"
        app:viewpager_color="@color/colorPrimary"
        app:viewpager_headerHeight="200dp"
        app:viewpager_headerAlpha="1.0"
        app:viewpager_hideLogoWithFade="false"
        app:viewpager_hideToolbarAndTitle="true"
        app:viewpager_enableToolbarElevation="true"
        app:viewpager_parallaxHeaderFactor="1.5"
        app:viewpager_headerAdditionalHeight="20dp"
        app:viewpager_displayToolbarWhenSwipe="true"
        app:viewpager_transparentToolbar="true"
        app:viewpager_animatedHeaderImage="true"
        app:viewpager_disableToolbar="false"

        />
</RelativeLayout>

**Comment by bloder** [comment]
Hello! Look my MaterialViewPager example maybe can help you with this null pointer - https://github.com/bloder/megan-fox-layout

**Comment by hindber** [comment]
Thank's , I fixed the problem.
