### ISSUE TITLE
You cannot start a load for a destroyed activity

### ISSUE THREAD

**Issue by hmathur127** [florent37/MaterialViewPager#307]
FATAL EXCEPTION: main
                                                                            Process: my.hollywood.data.collection, PID: 9225
                                                                            java.lang.IllegalArgumentException: You cannot start a load for a destroyed activity
                                                                                at com.bumptech.glide.manager.RequestManagerRetriever.assertNotDestroyed(RequestManagerRetriever.java:134)
                                                                                at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:102)
                                                                                at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:87)
                                                                                at com.bumptech.glide.Glide.with(Glide.java:629)
                                                                                at com.github.florent37.materialviewpager.header.MaterialViewPagerImageHelper$1.onAnimationEnd(MaterialViewPagerImageHelper.java:42)
                                                                                at android.support.v4.view.ViewPropertyAnimatorCompatJB$1.onAnimationEnd(ViewPropertyAnimatorCompatJB.java:47)
                                                                                at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationEnd(ViewPropertyAnimator.java:1114)
                                                                                at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1239)
                                                                                at android.animation.ValueAnimator$AnimationHandler.doAnimationFrame(ValueAnimator.java:766)
                                                                                at android.animation.ValueAnimator$AnimationHandler$1.run(ValueAnimator.java:801)
                                                                                at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                                                at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                                at android.view.Choreographer.doFrame(Choreographer.java:603)
                                                                                at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                                                at android.os.Handler.handleCallback(Handler.java:746)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                at android.os.Looper.loop(Looper.java:148)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5443)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
____________________________________________________________________________________________________________

due to Glide app crashing with above logcat.

after searching for solution i introduced to this " https://github.com/bumptech/glide/issues/803 "
solution but i don't know how to implement this solution to MaterialViewPager

**Comment by Stabja** [comment]
Use Glide.with(getApplicationContext())........

**Comment by hmathur127** [comment]
not working for me :(

**Comment by Touchunit** [comment]
same problem someone help please!

**Comment by mugambbo** [comment]
I'm not sure if someone has found a solution to this, however, what worked for me was to call Glide.with(getApplicationContext()).resumeRequests(); **onCreate**, followed by Glide.with(getApplicationContext()).pauseRequests(); **onSaveInstanceState**. I guess this worked for me because mine was due to configuration changes.

**Comment by zjxuzhj** [comment]
Someone with the same question please help!

**Comment by arnyigor** [comment]
+1.Where is solutions?
