### ISSUE TITLE
You can't start or clear loads in RequestListener or Target callbacks

### ISSUE THREAD

**Issue by tinyCoder32** [florent37/MaterialViewPager#332]
Hi, thanks for this awesome library.

In my simple app, if i switch between tabs very fastly, the app crashs leaving this:

```co.my.araa E/AndroidRuntime: FATAL EXCEPTION: main
                                                                Process: co.my.araa, PID: 23545
                                                                java.lang.IllegalStateException: You can't start or clear loads in RequestListener or Target callbacks. If you must do so, consider posting your into() or clear() calls to the main thread using a Handler instead.
                                                                    at com.bumptech.glide.request.SingleRequest.assertNotCallingCallbacks(SingleRequest.java:279)
                                                                    at com.bumptech.glide.request.SingleRequest.clear(SingleRequest.java:296)
                                                                    at com.bumptech.glide.manager.RequestTracker.clearRemoveAndRecycle(RequestTracker.java:62)
                                                                    at com.bumptech.glide.RequestManager.untrack(RequestManager.java:443)
                                                                    at com.bumptech.glide.RequestManager.untrackOrDelegate(RequestManager.java:430)
                                                                    at com.bumptech.glide.RequestManager.clear(RequestManager.java:418)
                                                                    at com.bumptech.glide.RequestBuilder.into(RequestBuilder.java:380)
                                                                    at com.bumptech.glide.RequestBuilder.into(RequestBuilder.java:432)
                                                                    at com.github.florent37.materialviewpager.header.MaterialViewPagerImageHelper$1.onAnimationEnd(MaterialViewPagerImageHelper.java:63)
                                                                    at android.support.v4.view.ViewPropertyAnimatorCompatJB$1.onAnimationEnd(ViewPropertyAnimatorCompatJB.java:51)
                                                                    at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationEnd(ViewPropertyAnimator.java:1116)
                                                                    at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1171)
                                                                    at android.animation.ValueAnimator.cancel(ValueAnimator.java:1073)
                                                                    at android.view.ViewPropertyAnimator.animatePropertyBy(ViewPropertyAnimator.java:967)
                                                                    at android.view.ViewPropertyAnimator.animateProperty(ViewPropertyAnimator.java:923)
                                                                    at android.view.ViewPropertyAnimator.alpha(ViewPropertyAnimator.java:737)
                                                                    at android.support.v4.view.ViewPropertyAnimatorCompatICS.alpha(ViewPropertyAnimatorCompatICS.java:34)
                                                                    at android.support.v4.view.ViewPropertyAnimatorCompat$ICSViewPropertyAnimatorCompatImpl.alpha(ViewPropertyAnimatorCompat.java:374)
                                                                    at android.support.v4.view.ViewPropertyAnimatorCompat.alpha(ViewPropertyAnimatorCompat.java:706)
                                                                    at com.github.florent37.materialviewpager.header.MaterialViewPagerImageHelper.fadeIn(MaterialViewPagerImageHelper.java:81)
                                                                    at com.github.florent37.materialviewpager.header.MaterialViewPagerImageHelper$1$1.onResourceReady(MaterialViewPagerImageHelper.java:56)
                                                                    at com.github.florent37.materialviewpager.header.MaterialViewPagerImageHelper$1$1.onResourceReady(MaterialViewPagerImageHelper.java:47)
                                                                    at com.bumptech.glide.request.SingleRequest.onResourceReady(SingleRequest.java:555)
                                                                    at com.bumptech.glide.request.SingleRequest.onResourceReady(SingleRequest.java:530)
                                                                    at com.bumptech.glide.load.engine.EngineJob.handleResultOnMainThread(EngineJob.java:184)
                                                                    at com.bumptech.glide.load.engine.EngineJob$MainThreadCallback.handleMessage(EngineJob.java:288)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                    at android.os.Looper.loop(Looper.java:135)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5268)
                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                    at java.lang.reflect.Method.invoke(Method.java:372)
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902)
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:697)
```

**Comment by chkfung** [comment]
What's your glide version?

**Comment by PedroBarbosaPT** [comment]
@chkfung 
4.5.0
Having same problem
