### ISSUE TITLE
Using Glide's latest version crashes

### ISSUE THREAD

**Issue by PedroBarbosaPT** [florent37/MaterialViewPager#338]
java.lang.NoSuchMethodError: No virtual method into(Landroid/widget/ImageView;)Lcom/bumptech/glide/request/target/Target; in class Lcom/bumptech/glide/RequestBuilder; or its super classes (declaration of 'com.bumptech.glide.RequestBuilder' appears in /data/app/net.quarkapps.ezmeet-2/split_lib_dependencies_apk.apk)
                      at com.github.florent37.materialviewpager.header.MaterialViewPagerImageHelper$1.onAnimationEnd(MaterialViewPagerImageHelper.java:63)
                      at android.support.v4.view.ViewPropertyAnimatorCompat$1.onAnimationEnd(ViewPropertyAnimatorCompat.java:748)
                      at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationEnd(ViewPropertyAnimator.java:1121)
                      at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1149)
                      at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1309)
                      at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
                      at android.animation.AnimationHandler.-wrap2(AnimationHandler.java)
                      at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
                      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:925)
                      at android.view.Choreographer.doCallbacks(Choreographer.java:702)
                      at android.view.Choreographer.doFrame(Choreographer.java:635)
                      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:913)
                      at android.os.Handler.handleCallback(Handler.java:751)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6682)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

**Comment by memet569** [comment]
this problem occur at my app while getting image from firebase store

**Comment by NdroidDev** [comment]
I am also facing similar problem when using Algolia instantsearch-android 1.4.2 with Firebase-ui 3.2.1 and glide 4.5.0/4.4.0/4.6.1
Please let me know if you find the solution.

Error:
java.lang.NoSuchMethodError: No virtual method into(Landroid/widget/ImageView;)Lcom/bumptech/glide/request/target/Target; in class Lcom/bumptech/glide/RequestBuilder; or its super classes (declaration of 'com.bumptech.glide.RequestBuilder' appears in /data/app/com.realtimesig.android.edjio-1/split_lib_dependencies_apk.apk)
                                                                                 at com.algolia.instantsearch.ui.views.Hits$HitsAdapter.onBindViewHolder(Hits.java:512)
                                                                                 at com.algolia.instantsearch.ui.views.Hits$HitsAdapter.onBindViewHolder(Hits.java:409)
                                                                                 at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6508)
                                                                                 at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6541)
                                                                                 at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5484)
                                                                                 at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5750)
                                                                                 at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5589)
                                                                                 at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5585)
                                                                                 at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2231)
                                                                                 at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1558)
                                                                                 at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1518)
                                                                                 at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:610)
                                                                                 at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3719)
                                                                                 at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:3135)
                                                                                 at android.view.View.measure(View.java:19857)
                                                                                 at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
                                                                                 at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
                                                                                 at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
                                                                                 at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
                                                                                 at android.view.View.measure(View.java:19857)
                                                                                 at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
                                                                                 at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                                 at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
                                                                                 at android.view.View.measure(View.java:19857)
                                                                                 at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
                                                                                 at android.support.v7.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:400)
                                                                                 at android.view.View.measure(View.java:19857)
                                                                                 at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
                                                                                 at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                                 at android.view.View.measure(View.java:19857)
                                                                                 at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
                                                                                 at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
                                                                                 at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
                                                                                 at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
                                                                                 at android.view.View.measure(View.java:19857)
                                                                                 at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
                                                                                 at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                                 at com.android.internal.policy.DecorView.onMeasure(DecorView.java:689)
                                                                                 at android.view.View.measure(View.java:19857)
                                                                                 at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2275)
                                                                                 at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1366)
                                                                                 at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1619)
                                                                                 at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
                                                                                 at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6337)
                                                                                 at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
                                                                                 at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                                                                                 at android.view.Choreographer.doFrame(Choreographer.java:621)
                                                                                 at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
02-15 22:50:39.145 3114-3114/com.realtimesig.android.edjio E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:751)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                 at android.os.Looper.loop(Looper.java:154)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by memet569** [comment]
Actually main problem is in toolbar background images which is slowling moving. if you use drawable folder images instead of URL images the problem can not seen anymore.

For example:
HeaderDesign.fromColorAndDrawable(getResources().getColor(R.color.green), getResources().getDrawable(R.drawable.flying));

**Comment by PedroBarbosaPT** [comment]
Yeah, but I wan't to use an  url image :/

**Comment by zjxuzhj** [comment]
You are right. I use the local image

**Comment by berviantoleo** [comment]
Are this issue fixed? I still faced this issue using glide 4.6.1

**Comment by Midhilaj** [comment]
I am also facing this issue any solutions available<br> compile 'com.github.bumptech.glide:glide:4.0.0'

**Comment by luifer94** [comment]
> Are this issue fixed? I still faced this issue using glide 4.6.1

1 Clone the repository
2 Import Module
3 include ':materialviewpager' on your settings.gradle
4 put : implementation project(':materialviewpager') on your build.gradle app
5 Copy the dependencies etc from Cloned Project to your project
6 Copy 'bintray-android-v1.gradle' and 'install-v1.gradle' files from the cloned project(located in the gradle directory) to your gradle directory
