### ISSUE TITLE
maybe a bug?

### ISSUE THREAD

**Issue by kot32go** [florent37/MaterialViewPager#50]
after(sorry,I made a clerical error 'before') I set the mViewPager.setImageDrawable(bg_img,fadeDuration); when I scroll in this page,throws a java.lang.StackOverflowError
            at com.github.florent37.materialviewpager.MaterialViewPagerAnimator.onMaterialScrolled(MaterialViewPagerAnimator.java:194)
I deleted this code:
dispatchScrollOffset(source, minMax(0, yOffset, scrollMaxDp));

It woks,so it's a Bug?

**Comment by florent37** [comment]
can you send me the full log please ?

**Comment by kot32go** [comment]
ok
java.lang.StackOverflowError
            at com.github.florent37.materialviewpager.MaterialViewPagerAnimator.onMaterialScrolled(MaterialViewPagerAnimator.java:181)
            at com.github.florent37.materialviewpager.MaterialViewPagerAnimator$6.onScrollChanged(MaterialViewPagerAnimator.java:508)
            at com.github.ksoichiro.android.observablescrollview.ObservableScrollView.onScrollChanged(ObservableScrollView.java:81)
            at android.view.View.scrollTo(View.java:10617)
            at android.widget.ScrollView.scrollTo(ScrollView.java:1581)
            at com.github.florent37.materialviewpager.MaterialViewPagerAnimator.setScrollOffset(MaterialViewPagerAnimator.java:149)
            at com.github.florent37.materialviewpager.MaterialViewPagerAnimator.dispatchScrollOffset(MaterialViewPagerAnimator.java:120)
            at com.github.florent37.materialviewpager.MaterialViewPagerAnimator.onMaterialScrolled(MaterialViewPagerAnimator.java:195)
            at com.github.florent37.materialviewpager.MaterialViewPagerAnimator$6.onScrollChanged(MaterialViewPagerAnimator.java:508)
            at com.github.ksoichiro.android.observablescrollview.ObservableScrollView.onScrollChanged(ObservableScrollView.java:81)
            at android.view.View.scrollTo(View.java:10617)
            at android.widget.ScrollView.scrollTo(ScrollView.java:1581)
            at com.github.florent37.materialviewpager.MaterialViewPagerAnimator.setScrollOffset(MaterialViewPagerAnimator.java:149)
            at com.github.florent37.materialviewpager.MaterialViewPagerAnimator.dispatchScrollOffset(MaterialViewPagerAnimator.java:120)
            at com.github.florent37.materialviewpager.MaterialViewPagerAnimator.onMaterialScrolled(MaterialViewPagerAnimator.java:195)
            at com.github.florent37.materialviewpager.MaterialViewPagerAnimator$6.onScrollChanged(MaterialViewPagerAnimator.java:508)
            at com.github.ksoichiro.android.observablescrollview.ObservableScrollView.onScrollChanged(ObservableScrollView.java:81)
            at android.view.View.scrollTo(View.java:10617)
            at android.widget.ScrollView.scrollTo(ScrollView.java:1581)
            at com.github.florent37.materialviewpager.MaterialViewPagerAnimator.setScrollOffset(MaterialViewPagerAnimator.java:149)
            at com.github.florent37.materialviewpager.MaterialViewPagerAnimator.dispatchScrollOffset(MaterialViewPagerAnimator.java:120)
            at com.github.florent37.materialviewpager.MaterialViewPagerAnimator.onMaterialScrolled(MaterialViewPagerAnimator.java:195)
            at com.github.florent37.materialviewpager.MaterialViewPagerAnimator$6.onScrollChanged(MaterialViewPagerAnimator.java:508)
            at com.github.ksoichiro.android.observablescrollview.ObservableScrollView.onScrollChanged(ObservableScrollView.java:81)
            at android.view.View.scrollTo(View.java:10617)
            at android.widget.ScrollView.scrollTo(ScrollView.java:1581)
            at com.github.florent37.materialviewpager.MaterialViewPagerAnimator.setScrollOffset(MaterialViewPagerAnimator.java:149)
            at com.github.florent37.materialviewpager.MaterialViewPagerAnimator.dispatchScrollOffset(MaterialViewPagerAnimator.java:120)
            at com.github.florent37.materialviewpager.MaterialViewPagerAnimator.onMaterialScrolled(MaterialViewPagerAnimator.java:195)
            at com.github.florent37.materialviewpager.MaterialViewPagerAnimator$6.onScrollChanged(MaterialViewPagerAnimator.java:508)
            at com.github.ksoichiro.android.observablescrollview.ObservableScrollView.onScrollChanged(ObservableScrollView.java:81)
            at android.view.View.scrollTo(View.java:10617)
            at android.widget.ScrollView.scrollTo(ScrollView.java:1581)
            at com.github.florent37.materialviewpager.MaterialViewPagerAnimator.setScrollOffset(MaterialViewPagerAnimator.java:149)
            at com.github.florent37.materialviewpager.MaterialViewPagerAnimator.dispatchScrollOffset(MaterialViewPagerAnimator.java:120)
            at com.github.florent37.materialviewpager.MaterialViewPagerAnimator.onMaterialScrolled(MaterialViewPagerAnimator.java:195)
            at com.github.florent37.materialviewpager.MaterialViewPagerAnimator$6.onScrollChanged(MaterialViewPagerAnimator.java:508)
            at com.github.ksoichiro.android.observablescrollview.ObservableScrollView.onScrollChanged(Observa

that's all

**Comment by florent37** [comment]
can you try with the 1.0.5 please ?
