### ISSUE TITLE
onInterceptTouchEvent -App Crashes on touch 

### ISSUE THREAD

**Issue by RassProjects** [florent37/MaterialViewPager#73]
i am Newbie in android development,i am trying to implement your amazing library(Must Say!)
i followed Your sample as it is (except webview and Drawer ) but when i touch the view below tabs app crashes.
Please look at the issue i am sure i am making mistake..please correct me it will be very appreciable!

My Log Cat

![screenshot_2015-06-10-12-42-50-new](https://cloud.githubusercontent.com/assets/11206738/8076993/6d8ebb6a-0f6f-11e5-8089-f6fc2f0be408.png)

   06-10 12:29:33.290  15581-15581/kipl.android.satyam.traveldemo E/InputEventReceiver﹕ Exception dispatching input event.
06-10 12:29:33.290  15581-15581/kipl.android.satyam.traveldemo E/MessageQueue-JNI﹕ Exception in MessageQueue callback: handleReceiveCallback
06-10 12:29:33.316  15581-15581/kipl.android.satyam.traveldemo E/MessageQueue-JNI﹕ java.lang.NullPointerException
            at android.support.v7.widget.RecyclerView.onInterceptTouchEvent(RecyclerView.java:1636)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1827)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2241)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1904)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2241)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1904)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2241)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1904)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2241)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1904)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2241)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1904)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2241)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1904)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2241)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1904)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2241)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1904)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:1977)
            at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1427)
            at android.app.Activity.dispatchTouchEvent(Activity.java:2428)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:1925)
            at android.view.View.dispatchPointerEvent(View.java:7443)
            at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:3603)
            at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:3531)
            at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:4783)
            at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:4743)
            at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:4895)
            at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:179)
            at android.os.MessageQueue.nativePollOnce(Native Method)
            at android.os.MessageQueue.next(MessageQueue.java:128)
            at android.os.Looper.loop(Looper.java:151)
            at android.app.ActivityThread.main(ActivityThread.java:5371)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
            at dalvik.system.NativeStart.main(Native Method)
06-10 12:29:33.343  15581-15581/kipl.android.satyam.traveldemo E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.NullPointerException
            at android.support.v7.widget.RecyclerView.onInterceptTouchEvent(RecyclerView.java:1636)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1827)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2241)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1904)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2241)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1904)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2241)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1904)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2241)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1904)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2241)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1904)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2241)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1904)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2241)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1904)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2241)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1904)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:1977)
            at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1427)
            at android.app.Activity.dispatchTouchEvent(Activity.java:2428)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:1925)
            at android.view.View.dispatchPointerEvent(View.java:7443)
            at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:3603)
            at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:3531)
            at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:4783)
            at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:4743)
            at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:4895)
            at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:179)
            at android.os.MessageQueue.nativePollOnce(Native Method)
            at android.os.MessageQueue.next(MessageQueue.java:128)
            at android.os.Looper.loop(Looper.java:151)
            at android.app.ActivityThread.main(ActivityThread.java:5371)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
            at dalvik.system.NativeStart.main(Native Method)
06-10 12:29:33.490

**Comment by florent37** [comment]
because you don't have a layoutmanager or cells ?

**Comment by RassProjects** [comment]
Thank U for your quick responce 
I followed Your Sample fully 
can you please suggest me any example how do we add Layout Manager or cells ...?

**Comment by florent37** [comment]
https://github.com/florent37/MaterialViewPager/blob/master/sample/src/main/java/com/github/florent37/materialviewpager/sample/fragment/RecyclerViewFragment.java

        RecyclerView.LayoutManager layoutManager = new LinearLayoutManager(getActivity());
        mRecyclerView.setLayoutManager(layoutManager);

**Comment by RassProjects** [comment]
i already did this sir
