### ISSUE TITLE
[Question] NullPointerException in AS Preview

### ISSUE THREAD

**Issue by DDerTyp** [florent37/MaterialViewPager#8]
Hey,
I am new to your Material ViewPager and not sure if it is an issue or not. When copying your code (from README, "Usage") into my layout, this error appears in the Android Studio Design Tab:

`java.lang.NullPointerException
	at com.github.florent37.materialviewpager.MaterialViewPager.onFinishInflate(MaterialViewPager.java:70)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:814)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:64)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:782)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:809)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:64)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:782)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:385)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:400)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:332)
	at com.android.ide.common.rendering.LayoutLibrary.createSession(LayoutLibrary.java:350)
	at com.android.tools.idea.rendering.RenderTask$2.compute(RenderTask.java:497)
	at com.android.tools.idea.rendering.RenderTask$2.compute(RenderTask.java:485)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:894)
	at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:485)
	at com.android.tools.idea.rendering.RenderTask.render(RenderTask.java:590)
	at com.intellij.android.designer.designSurface.AndroidDesignerEditorPanel$6.run(AndroidDesignerEditorPanel.java:480)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:320)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:310)
	at com.intellij.util.ui.update.MergingUpdateQueue$2.run(MergingUpdateQueue.java:254)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:269)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:227)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:217)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:351)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`

My Code in Android Studio:
`<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools" xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent" tools:context=".MainActivity">

    <com.github.florent37.materialviewpager.MaterialViewPager
        android:id="@+id/materialViewPager"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:viewpager_logo="@layout/header_logo"
        app:viewpager_logoMarginTop="100dp"
        app:viewpager_color="@color/colorPrimary"
        app:viewpager_headerHeight="200dp"
        app:viewpager_headerAlpha="1.0"
        app:viewpager_hideLogoWithFade="true"
        app:viewpager_hideToolbarAndTitle="true"
        app:viewpager_enableToolbarElevation="true"
        />

</RelativeLayout>
`

What can I do?

Regards,
DDerTyp

**Comment by florent37** [comment]
Hi,

at line 70 I have the following code : 
                    'headerBackgroundContainer.addView(LayoutInflater.from(getContext()).inflate(settings.headerLayoutId, headerBackgroundContainer, false));'

reading your issue it's `LayoutInflater.from(getContext()` has an issue 

can you try set a custom layout as header : 

header.xml
    	<?xml version="1.0" encoding="utf-8"?>
	    <com.github.florent37.materialviewpager.MaterialViewPagerImageHeader
	    xmlns:android="http://schemas.android.com/apk/res/android"
	    android:id="@id/materialviewpager_imageHeader"
	    android:layout_width="match_parent"
	    android:layout_height="match_parent"
	    android:adjustViewBounds="true"
	    android:scaleType="centerCrop" />

and in your materialviewpager :
    app:viewpager_header="@layout/header.xml"

I am creating a new project and import my lib from gradle to check if I have the same issue

**Comment by florent37** [comment]
Ok it's just because **header_logo.xml** was only defined on my sample project,
I update the readme to alert create your own header layoit

mine was

	<?xml version="1.0" encoding="utf-8"?>
	<TextView xmlns:android="http://schemas.android.com/apk/res/android"
	    android:id="@+id/logo_white"
	    android:layout_width="wrap_content"
	    android:layout_height="@dimen/materialviewpager_logoHeight"
	    android:text="Material is Good"
	    android:textSize="30sp"
	    android:textColor="@android:color/white"/>

**Comment by florent37** [comment]
I send you my empty project if you want to test : 

https://github.com/florent37/TutosAndroidFrance/tree/master/MaterialViewPagerSample

can you confilm me it's working, so I can close this issue ?

**Comment by DDerTyp** [comment]
Hey,
thanks for your fast reply, but I already implemented the header_logo.xml!
The issue with the Android Studio Design preview is still present - exact the same Rendering Problem. The App looks like this:
![device-2015-05-04-223032](https://cloud.githubusercontent.com/assets/4542310/7461831/33958c9c-f2ad-11e4-8008-4bd84d0646c5.png)

**Comment by florent37** [comment]
look again my Readme I added a section about the style : https://github.com/florent37/MaterialViewPager#usage

**Comment by DDerTyp** [comment]
Works fine now, thanks!
One last (issue?):
I got a "AppCompat does not support the current theme features"-bug. Had to add ´<item name="windowNoTitle">true</item>´ to the styles under windowActionBar.

Thanks for your patience!

**Comment by florent37** [comment]
it's a current bug with appcompat 22.1.1, try to return at 22.0.0

**Comment by DDerTyp** [comment]
Okay, thanks for the information!

**Comment by florent37** [comment]
information : I updated my empty sample
https://github.com/florent37/TutosAndroidFrance/tree/master/MaterialViewPagerSample

with an adapter & style

**Comment by florent37** [comment]
![capture d ecran 2015-05-04 a 22 51 40](https://cloud.githubusercontent.com/assets/5754972/7462221/30f408b2-f2b0-11e4-8e39-ae0bf200d29c.png)
![device-2015-05-04-225147](https://cloud.githubusercontent.com/assets/5754972/7462220/30f1be0e-f2b0-11e4-9864-b706080c6a92.png)
